name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start server
        run: |
          python server.py &
          sleep 5  # Ждем, пока сервер запустится

      - name: Run tests
        run: |
          pytest --cov=server tests/

      - name: Check coverage
        run: |
          coverage report --fail-under=100

      - name: Lint code
        run: |
          flake8 .
